### ISSUE TITLE
Statically compiled

### ISSUE THREAD

**Issue by ghost** [moul/xz-utils-static-builder#1]
Could some instructions be added? I can not get xz to compile statically...

**Comment by moul** [comment]
Hi @shevegen I added a Makefile which should do everything for you and may be considered as instructions too :)

**Comment by coolaj86** [comment]
For others still looking for an answer:

I think that these are the most up-to-date instructions, using the official repository and make file:

```bash
wget https://tukaani.org/xz/xz-5.2.5.tar.gz
tar xvf xz-5.2.5.tar.gz
pushd ./xz-5.2.5/
./configure --disable-debug --disable-dependency-tracking --disable-silent-rules --disable-shared --disable-nls
make

rsync -av src/xz/xz ~/.local/bin/
ln -s xz ~/.local/bin/unxz
```

I've published the static builds I created for Mac and Linux x64:

- [webinstall.dev/xz](https://webinstall.dev/xz/)
- [github.com/therootcompany/xz-static](https://github.com/therootcompany/xz-static/releases)

I'd love help getting that for Linux aarch64 and the new Mac M1 too.

I'd also be interested in understanding why the gcc options in the Dockerfile are given and if they can be included in the `./configure` process.
